" All system-wide defaults are set in $VIMRUNTIME/archlinux.vim (usually just
" /usr/share/vim/vimfiles/archlinux.vim) and sourced by the call to :runtime
" you can find below.  If you wish to change any of those settings, you should
" do it in this file (/etc/vimrc), since archlinux.vim will be overwritten
" everytime an upgrade of the vim packages is performed.  It is recommended to
" make changes after sourcing archlinux.vim since it alters the value of the
" 'compatible' option.

" This line should not be removed as it ensures that various options are
" properly set to work with the Vim-related packages.
runtime! archlinux.vim

" If you prefer the old-style vim functionalty, add 'runtime! vimrc_example.vim'
" Or better yet, read /usr/share/vim/vim80/vimrc_example.vim or the vim manual
" and configure vim to your own liking!

" do not load defaults if ~/.vimrc is missing
"let skip_defaults_vim=1
" Ensure defaults are set before customizing settings, not after

set ruler
set background=dark
set backspace=eol,start,indent
set whichwrap+=<,>,h,s
syntax enable
set encoding=utf8
set ffs=unix,dos
set nobackup
set nowb
set noswapfile
set expandtab
set smarttab
set shiftwidth=4
set tabstop=4
set lbr
set ai
set si
set wrap
set hlsearch
set showmatch
set breakindent
set formatoptions+=l,n
set clipboard=unnamedplus

let mapleader = ","

nnoremap <CR> :noh<CR><CR>

autocmd FileType c,cpp,objc nnoremap <buffer><Leader>cf :<C-u>ClangFormat<CR>
autocmd FileType c,cpp,objc vnoremap <buffer><Leader>cf :ClangFormat<CR>

let wiki = {}
let wiki.path = '~/wiki/'
let g:vimwiki_list = [wiki]
let g:vimwiki_list_ignore_newline = 0
