" Ensure defaults are set before customizing settings, not after
source $VIMRUNTIME/defaults.vim
let skip_defaults_vim=1 

set ruler
set background=dark
set backspace=eol,start,indent
set whichwrap+=<,>,h,s
syntax enable
set encoding=utf8
set ffs=unix,dos
set nobackup
set nowb
set noswapfile
set expandtab
set smarttab
set shiftwidth=4
set tabstop=4
set lbr
set ai
set si
set wrap
set hlsearch
set showmatch
set breakindent
set formatoptions+=l,n
set clipboard=unnamedplus

let mapleader = ","

nnoremap <CR> :noh<CR><CR>

autocmd FileType c,cpp,objc nnoremap <buffer><Leader>cf :<C-u>ClangFormat<CR>
autocmd FileType c,cpp,objc vnoremap <buffer><Leader>cf :ClangFormat<CR>
